### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by balbalu** [bp0lr/dmut#1]
![issue](https://user-images.githubusercontent.com/38427882/102003348-2c898f00-3d2c-11eb-9a8b-7bf9ea3e19c1.png)

when I am trying to run I am not getting any output.

**Comment by bp0lr** [comment]
hello!
run the same command using the --show-stats flag to check how many DNS servers you are using and the total amount of errors for each one.

You can also run dmut with --dns-errorLimit and play with the limits. (the default number is 25).

let me know.

**Comment by bp0lr** [comment]
also, try running this to update the default DNS servers list
`dmut --update-dnslist`
