### ISSUE TITLE
Avoid default 1-9 Values

### ISSUE THREAD

**Issue by jaikishantulswani** [bp0lr/dmut#10]
@bp0lr Is there any way to avoid permutations with 1-9 which are generated by default.
like 1.example.com to 9.example.com

**Comment by bp0lr** [comment]
Hello!,

now you can.

 --disable-addnumbers     Disable add numbers generation
--disable-addseparator   Disable add separator generation
--disable-permutations   Disable permutations generation

**Comment by bp0lr** [comment]
just update dmut to his last version

go get -u github.com/bp0lr/dmut

and confirm if you have the new flags.

**Comment by jaikishantulswani** [comment]
Thank you @bp0lr This is superfast !
