### ISSUE TITLE
Save file location

### ISSUE THREAD

**Issue by jaikishantulswani** [bp0lr/dmut#12]
@bp0lr It would be good if it have a flag to save `--save-gen` generated list to a provided location, as now it is saving `generated.txt` to the current directory by default.

**Comment by bp0lr** [comment]
sure, you can use --save-to from now on.

remember to update your dmut installation.

go get -u github.com/bp0lr/dmut

**Comment by jaikishantulswani** [comment]
@bp0lr Super :100:
