### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tk-t0n0y** [bp0lr/dmut#2]
![IMG_20201213_215122](https://user-images.githubusercontent.com/75567610/102016887-7bb3dc00-3d8d-11eb-88fa-1e802dc57c2b.jpg)

**Comment by bp0lr** [comment]
Hello!,
sound like something related to your GO installation.
You need at less golang 1.15
You can install the last version of golang using the script from here:
(https://github.com/canha/golang-tools-install-script)

one liner
`wget -q -O - https://git.io/vQhTU | bash`
