### ISSUE TITLE
No Output

### ISSUE THREAD

**Issue by 0xspade** [bp0lr/dmut#3]
Tried every command in the README still no output

tried everything [here](https://github.com/bp0lr/dmut/issues/1) and still no output.

**Comment by bp0lr** [comment]
Hello!

Please, follow these steps and tell me what happens

lets update dmut to the last version
`
go get -u github.com/bp0lr/dmut
`

update the files we need to work
`
dmut --update-files
`

do a test job to check what happens.
`
dmut -u "powercoaching.redbull.com" -s /root/.dmut/resolvers.txt -d /root/.dmut/words.txt
`

your output should be 
```
powercoaching-admin.redbull.com
powercoaching2.redbull.com
powercoaching-q.redbull.com
```

If you didn't get anything from dmut, run the same command using the -v and --show-stats flags.

**Comment by 0xspade** [comment]
this command:

`dmut -u "powercoaching.redbull.com" -s /root/.dmut/resolvers.txt -d /root/.dmut/words.txt` is working

but when I try:

`cat subdomains.txt | dmut -s /root/.dmut/resolvers.txt -d /root/.dmut/words.txt` 

it's not working

**Comment by bp0lr** [comment]
You can try using the flag -v and --show-stats.
In other case, I will need to see what do you have in subdomains.txt.
Maybe is something related to the list format or maybe your list just doesn't return any result.
