### ISSUE TITLE
Premute Output

### ISSUE THREAD

**Issue by jaikishantulswani** [bp0lr/dmut#4]
@bp0lr It would be good if it have a flag to save only output of permutation / alterations without resolving them.

Thank You.

**Comment by bp0lr** [comment]
Sure, that an easy one.

--save-gen was added.

**Comment by jaikishantulswani** [comment]
@bp0lr thank you for this super fast change, having issue while generating premutations containing only a domain like example.com. As dmut only create permutations with subdomains like test.example.com not with example.com
It would be very useful if it also create permutations / alterations with single domains only.

Thank you

**Comment by bp0lr** [comment]
dmut need at less one subdomain to be able to permute / alterare / attach.
The main function of the tool is that.

If you need something to generate a subdomain list based on a main domain, there is plenty of tool for that.

**Comment by jaikishantulswani** [comment]
@bp0lr I know there a many tools to do that same but dmut is creating some extra premutations with the provided list comparing to other tools that is why I am requesting you to please add this too.

**Comment by bp0lr** [comment]
yea, but I'm not understanding how.

for example, you have the domain main.com, and a word list with a,b,c.

you want dmut to generate a.main.com a-.main.com, a1.main.com... and the same for b,c?

If you can be a bit more clear maybe this is something that I didn't see.

**Comment by jaikishantulswani** [comment]
@bp0lr Yes I wan't dmut to generate a list by taking domain main.com to 
a.main.com
a1.main.com
1a.main.com
a-1.main.com
1-a.main.com 
and so on with the word list provided

Thank you

**Comment by bp0lr** [comment]
sure, let do this without touching the code ;)

file 1, the subdomains that you want.
```
host1
host2
host3
```

file 2, the permutation list
```
dev
stage
q
```

one-liner
`while IFS= read -r line;do echo "$line.example.com"; done <t.txt | dmut -d short.txt --save-gen`

```
cat generated.txt

dev.host3.example.com
host3-5.example.com
host30.example.com
host33.example.com
host1.stage.example.com
host19.example.com
host1-dev.example.com
stage.host1.example.com
host1.dev.example.com
host1-0.example.com
host11.example.com
qhost1.example.com
```
you just need to change the main domain and fix the files name to match what are you doing.

**Comment by jaikishantulswani** [comment]
@bp0lr done :+1: but it would be much more smooth if its done on the go by dmut , hope you consider it and add a switch to do the same process.

Thank you

**Comment by jaikishantulswani** [comment]
@bp0lr If this still not sound good, can you please do only one thing in dmut to accept the file containing parent domain only and then do alterations by supplied list like:
```
cat domain.txt
example.com
```
```
cat words.txt
a
b
c
```

cat domain.txt | dmut -d words.txt --save-gen

**Comment by jaikishantulswani** [comment]
@bp0lr waiting for your response.

**Comment by bp0lr** [comment]
I have added an option for situations where dmut need to work just with a main domain.

the subdomain list will be generated based on the mutations list, but no mutation / permutation will take place based on how this works.

for example, if you use dmut with the domain example.com, the list will be something like a.example.com b.example.com c.example.com.

You need to update dmut
` go get -u github.com/bp0lr/dmut`

**Comment by jaikishantulswani** [comment]
@bp0lr Thank you :100:
