### ISSUE TITLE
Library Improvement?

### ISSUE THREAD

**Issue by java-apocalypse** [bp0lr/dmut#7]
Hello, in what the code here https://github.com/bp0lr/dmut/blob/main/dns/dns.go differs from https://github.com/projectdiscovery/retryabledns/blob/master/client.go? Is there any improvement?

**Comment by bp0lr** [comment]
I'm not sure to call it improvements, but I have modified the original version to support for example:

* error Limit
* dns timeout
* dns truncation
* retry using TCP if UDP fails

**Comment by java-apocalypse** [comment]
I think it would be nice to send a PR upstream if this is an improvement or add credits
